AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Metadata:
  PatternTransform:
    Properties:
      - JSONPath: $.[object Object]
        Message: Hello
        InputType: string
    Placeholders: []
Resources:
  MySqsQueue:
    Type: AWS::SQS::Queue
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventRule
      Targets:
        - Arn: !GetAtt MySqsQueue.Arn
  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt MySqsQueue.Arn
      Queues:
        - !Ref MySqsQueue
